{% set name = "bertopic" %}
{% set version = "0.15.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bertopic-{{ version }}.tar.gz
  sha256: b7fe931a727e00c00ff42ef974fd63b83621c30a9259ed32fceaa7c934845eaf
build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy >=1.20.0
    - hdbscan >=0.8.29
    - umap-learn >=0.5.0
    - pandas >=1.1.5
    - scikit-learn >=0.22.2.post1
    - tqdm >=4.41.1
    - sentence-transformers >=0.4.1
    - plotly >=4.7.0

test:
  imports:
    - bertopic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MaartenGr/BERTopic
  summary: BERTopic performs topic Modeling with state-of-the-art transformer models.
  license: MIT
  license_file: LICENSE
  description: |
    BERTopic is a topic modeling technique that leverages transformers and c-TF-IDF to
    create dense clusters allowing for easily interpretable topics whilst keeping important
    words in the topic descriptions.
  doc_url: https://maartengr.github.io/BERTopic/

extra:
  recipe-maintainers:
    - mimshiran
    - MaartenGr
