{% set name = "bertopic" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bertopic-{{ version }}.tar.gz
  sha256: 96dae6e64b1d9e4ecb65ee97623e7451d00275d53515a3e5fe36adff6f5517e1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: True  # [py<38 or s390x or ppc64le]
  
  # ppc64le has numerous conflicts within the required
  # dependencies that we will revist at a later time.

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    # To avoid umap-learn/numpy/numba incompatibility we need numpy<1.24
    - numpy >=1.20.0,!=1.22.0,!=1.22.1,!=1.22.2,<1.24
    - hdbscan >=0.8.29
    - umap-learn >=0.5.0
    - pandas >=1.1.5
    - scikit-learn >=0.22.2.post1
    - tqdm >=4.41.1
    - sentence-transformers >=0.4.1
    - plotly >=4.7.0


test:
  imports:
    - bertopic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MaartenGr/BERTopic
  summary: BERTopic performs topic Modeling with state-of-the-art transformer models.
  license: MIT
  license_family: MIT
  license_url: https://github.com/MaartenGr/BERTopic/blob/master/LICENSE
  description: |
    BERTopic is a topic modeling technique that leverages transformers and c-TF-IDF to
    create dense clusters allowing for easily interpretable topics whilst keeping important
    words in the topic descriptions.
  doc_url: https://maartengr.github.io/BERTopic/
  dev_url: https://maartengr.github.io/BERTopic/changelog.html

extra:
  recipe-maintainers:
    - mimshiran
    - MaartenGr
